// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
std::string compressToEncodedURIComponent(std::string uncompressed8);
extern "C" SEXP _shinylive_compressToEncodedURIComponent(SEXP uncompressed8) {
  BEGIN_CPP11
    return cpp11::as_sexp(compressToEncodedURIComponent(cpp11::as_cpp<cpp11::decay_t<std::string>>(uncompressed8)));
  END_CPP11
}
// code.cpp
std::string decompressFromEncodedURIComponent(std::string compressed8);
extern "C" SEXP _shinylive_decompressFromEncodedURIComponent(SEXP compressed8) {
  BEGIN_CPP11
    return cpp11::as_sexp(decompressFromEncodedURIComponent(cpp11::as_cpp<cpp11::decay_t<std::string>>(compressed8)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_shinylive_compressToEncodedURIComponent",     (DL_FUNC) &_shinylive_compressToEncodedURIComponent,     1},
    {"_shinylive_decompressFromEncodedURIComponent", (DL_FUNC) &_shinylive_decompressFromEncodedURIComponent, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_shinylive(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
