# Generated by cpp11: do not edit by hand

compressToEncodedURIComponent <- function(uncompressed8) {
  .Call(`_shinylive_compressToEncodedURIComponent`, uncompressed8)
}

decompressFromEncodedURIComponent <- function(compressed8) {
  .Call(`_shinylive_decompressFromEncodedURIComponent`, compressed8)
}
